language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

install:
 - pip install coveralls

script: coverage run --source vbe_decoder setup.py test
after_success:
  - coveralls --config_file .coveragerc